
import { Product, ProductType, Testimonial, BlogPost, User, Order } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Advanced Calculus Notes',
    description: 'Comprehensive notes covering all topics in a typical Advanced Calculus course.',
    price: 19.99,
    imageUrl: 'https://picsum.photos/seed/calculus/600/400',
    type: ProductType.NOTES,
    subject: 'Mathematics',
    university: 'Stanford University',
    rating: 4.8,
    reviewsCount: 150,
    author: 'Dr. Jane Doe',
    pages: 200,
    createdAt: '2023-10-01',
  },
  {
    id: '2',
    name: 'Introduction to Python Programming',
    description: 'A beginner-friendly e-book for learning Python from scratch.',
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/python/600/400',
    type: ProductType.EBOOK,
    subject: 'Computer Science',
    university: 'MIT',
    rating: 4.9,
    reviewsCount: 320,
    author: 'John Smith',
    pages: 350,
    createdAt: '2023-09-15',
  },
  {
    id: '3',
    name: 'Marketing 101 Presentation',
    description: 'A ready-made PowerPoint presentation on the fundamentals of marketing.',
    price: 9.99,
    imageUrl: 'https://picsum.photos/seed/marketing/600/400',
    type: ProductType.PPT,
    subject: 'Business',
    university: 'Harvard University',
    rating: 4.5,
    reviewsCount: 85,
    author: 'Emily White',
    pages: 50,
    createdAt: '2023-11-05',
  },
  {
    id: '4',
    name: 'Organic Chemistry Study Guide',
    description: 'A detailed PDF study guide for acing your Organic Chemistry exams.',
    price: 24.99,
    imageUrl: 'https://picsum.photos/seed/chemistry/600/400',
    type: ProductType.PDF,
    subject: 'Chemistry',
    university: 'UC Berkeley',
    rating: 4.7,
    reviewsCount: 210,
    author: 'Dr. Michael Brown',
    pages: 180,
    createdAt: '2023-08-20',
  },
  {
    id: '5',
    name: 'History of Modern Europe',
    description: 'An engaging e-book covering European history from the French Revolution to the present.',
    price: 34.99,
    imageUrl: 'https://picsum.photos/seed/history/600/400',
    type: ProductType.EBOOK,
    subject: 'History',
    university: 'University of Oxford',
    rating: 4.9,
    reviewsCount: 180,
    author: 'Prof. Eleanor Vance',
    pages: 500,
    createdAt: '2023-11-10',
  },
    {
    id: '6',
    name: 'Introduction to Microeconomics',
    description: 'Complete lecture notes and problem sets for an introductory microeconomics course.',
    price: 22.50,
    imageUrl: 'https://picsum.photos/seed/economics/600/400',
    type: ProductType.NOTES,
    subject: 'Economics',
    university: 'University of Chicago',
    rating: 4.6,
    reviewsCount: 130,
    author: 'Dr. Samuel Green',
    pages: 250,
    createdAt: '2023-07-30',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Computer Science Student',
    quote: 'The Python e-book from AcademicSorcess was a lifesaver! It made complex topics so easy to understand. Highly recommended!',
    avatarUrl: 'https://picsum.photos/seed/person1/100/100',
  },
  {
    id: '2',
    name: 'David Chen',
    role: 'Pre-Med Student',
    quote: 'I was struggling with Organic Chemistry, but the study guide helped me organize my learning and I ended up with an A. Thank you!',
    avatarUrl: 'https://picsum.photos/seed/person2/100/100',
  },
  {
    id: '3',
    name: 'Maria Rodriguez',
    role: 'Business Major',
    quote: 'The marketing presentation was professional and saved me so much time. It was the perfect starting point for my project.',
    avatarUrl: 'https://picsum.photos/seed/person3/100/100',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Top 5 Study Habits for University Success',
    excerpt: 'Discover the most effective study habits that will help you excel in your university courses and achieve your academic goals.',
    content: '<p>Content for blog post 1...</p>',
    author: 'AcademicSorcess Team',
    date: 'November 15, 2023',
    imageUrl: 'https://picsum.photos/seed/blog1/800/600',
    tags: ['Study Tips', 'Productivity'],
  },
  {
    id: '2',
    title: 'How to Choose the Right Major For You',
    excerpt: 'Choosing a major is a big decision. Here are some tips and strategies to help you find the perfect field of study for your interests and career aspirations.',
    content: '<p>Content for blog post 2...</p>',
    author: 'Dr. Amanda White',
    date: 'October 28, 2023',
    imageUrl: 'https://picsum.photos/seed/blog2/800/600',
    tags: ['Academics', 'Career'],
  },
  {
    id: '3',
    title: 'Mastering Time Management in College',
    excerpt: 'Juggling classes, assignments, and a social life can be tough. Learn how to manage your time effectively and reduce stress.',
    content: '<p>Content for blog post 3...</p>',
    author: 'John Smith',
    date: 'October 10, 2023',
    imageUrl: 'https://picsum.photos/seed/blog3/800/600',
    tags: ['Time Management', 'Student Life'],
  },
];

export const USERS: User[] = [
    { id: '1', name: 'Admin User', email: 'admin@academicsorcess.com', role: 'admin', createdAt: '2023-01-01' },
    { id: '2', name: 'John Doe', email: 'john.doe@example.com', role: 'customer', createdAt: '2023-05-10' },
    { id: '3', name: 'Jane Smith', email: 'jane.smith@example.com', role: 'customer', createdAt: '2023-06-15' },
    { id: '4', name: 'Peter Jones', email: 'peter.jones@example.com', role: 'customer', createdAt: '2023-07-20' },
];

export const ORDERS: Order[] = [
    { 
        id: 'ORD-001', 
        userId: '2', 
        userName: 'John Doe', 
        date: '2023-11-10', 
        total: 19.99, 
        status: 'Completed',
        items: [{productId: '1', productName: 'Advanced Calculus Notes', quantity: 1, price: 19.99}]
    },
    { 
        id: 'ORD-002', 
        userId: '3', 
        userName: 'Jane Smith', 
        date: '2023-11-08', 
        total: 39.98, 
        status: 'Completed',
        items: [
            {productId: '2', productName: 'Introduction to Python Programming', quantity: 1, price: 29.99},
            {productId: '3', productName: 'Marketing 101 Presentation', quantity: 1, price: 9.99},
        ]
    },
    { 
        id: 'ORD-003', 
        userId: '4', 
        userName: 'Peter Jones', 
        date: '2023-11-05', 
        total: 24.99, 
        status: 'Pending',
        items: [{productId: '4', productName: 'Organic Chemistry Study Guide', quantity: 1, price: 24.99}]
    },
     { 
        id: 'ORD-004', 
        userId: '2', 
        userName: 'John Doe', 
        date: '2023-10-25', 
        total: 34.99, 
        status: 'Refunded',
        items: [{productId: '5', productName: 'History of Modern Europe', quantity: 1, price: 34.99}]
    },
];
